"""Direct and API HTTP relay for Frappe Cloud.

Public requests are forwarded to the configured upstream and the upstream
status, body, and response headers are restored after Frappe builds its WSGI
response.  Frappe administration and static/API routes remain available.
"""
from __future__ import annotations

from urllib.parse import urlsplit, urlunsplit

import frappe
import requests
from werkzeug.exceptions import BadRequest, Forbidden, HTTPException
from werkzeug.wrappers import Response

_DROP_HEADERS = {
    "host",
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    "forwarded",
    "x-forwarded-host",
    "x-forwarded-proto",
    "x-forwarded-port",
    "content-length",
    "content-encoding",
}

_EXEMPT_PREFIXES = (
    "/api/",
    "/assets/",
    "/files/",
    "/private/files/",
    "/app",
    "/desk",
    "/login",
    "/setup",
    "/socket.io",
    "/backups",
    "/.well-known/",
)


class _RelayHTTPResponse(HTTPException):
    """Escape hatch for Frappe's before_request hook, which ignores returns."""

    def __init__(self, body: bytes, status: int, headers: dict[str, str]):
        self._relay_response = Response(body, status=status, headers=headers)
        super().__init__()

    def get_response(self, environ=None):
        return self._relay_response


def _setting(name: str, default=None):
    return frappe.conf.get(name, default)


def _base_target() -> tuple[str, str]:
    base = (_setting("back4app_relay_target_domain") or "https://vps.thumbayan.com:443").rstrip("/")
    parsed = urlsplit(base)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise frappe.ValidationError("back4app_relay_target_domain must be an http(s) URL")
    return parsed.scheme, parsed.netloc


def _target_url(path: str) -> str:
    scheme, netloc = _base_target()
    parsed_path = urlsplit(path or "/")
    safe_path = parsed_path.path or "/"
    return urlunsplit((scheme, netloc, safe_path, parsed_path.query, ""))


def _request_headers() -> dict[str, str]:
    incoming = frappe.request.headers
    headers: dict[str, str] = {}
    client_ip = incoming.get("X-Real-IP") or incoming.get("X-Forwarded-For")
    for key, value in incoming.items():
        lower = key.lower()
        if lower in _DROP_HEADERS or lower == "x-relay-token" or lower.startswith("x-vercel-"):
            continue
        headers[key] = value
    if client_ip:
        headers["X-Forwarded-For"] = client_ip
    headers["X-Forwarded-Proto"] = "https" if frappe.request.scheme == "https" else "http"
    headers["X-Forwarded-Host"] = frappe.request.host
    return headers


def _token_is_valid() -> bool:
    configured_token = _setting("back4app_relay_token")
    return not configured_token or frappe.request.headers.get("X-Relay-Token") == configured_token


def _fetch_upstream(target: str) -> tuple[int, bytes, dict[str, str]]:
    try:
        upstream = requests.request(
            method=frappe.request.method.upper(),
            url=target,
            headers=_request_headers(),
            data=frappe.request.get_data(cache=True),
            timeout=(10, 120),
            allow_redirects=False,
        )
    except requests.RequestException:
        frappe.log_error(frappe.get_traceback(), "Back4App XHTTP Relay upstream failure")
        return 502, b"Bad Gateway: Proxy request failed", {"content-type": "text/plain; charset=utf-8"}

    # requests collapses repeated headers, which is sufficient for this
    # upstream.  Hop-by-hop and framing headers are regenerated by WSGI.
    response_headers = {
        key: value for key, value in upstream.headers.items() if key.lower() not in _DROP_HEADERS
    }
    return upstream.status_code, upstream.content, response_headers


def _is_exempt(path: str) -> bool:
    return any(path == prefix.rstrip("/") or path.startswith(prefix) for prefix in _EXEMPT_PREFIXES)


def relay_before_request():
    """Return the upstream WSGI response directly for public requests.

    Returning a Werkzeug Response from a Frappe before_request hook bypasses
    Frappe's JSON/binary response builder, which otherwise replaces an empty
    upstream body with ``{}`` and drops end-to-end headers.
    """
    path = frappe.request.path or "/"
    if _is_exempt(path):
        return None
    if not _token_is_valid():
        return Response("Forbidden", status=403, content_type="text/plain")
    query = frappe.request.query_string.decode() if frappe.request.query_string else ""
    original_path = f"{path}?{query}" if query else path
    status, body, headers = _fetch_upstream(_target_url(original_path))
    # Frappe ignores return values from before_request hooks. Raising an
    # HTTPException makes frappe.app.application use get_response() directly.
    raise _RelayHTTPResponse(body, status, headers)


@frappe.whitelist(allow_guest=True)
def health():
    """Simple health endpoint for monitoring without contacting upstream."""
    return {"status": "ok", "upstream": _setting("back4app_relay_target_domain") or "https://vps.thumbayan.com:443"}


@frappe.whitelist(allow_guest=True)
def relay(path: str | None = None):
    """Fetch upstream and hand raw response data to the after-request hook."""
    if not _token_is_valid():
        raise Forbidden("Invalid relay token")
    method = frappe.request.method.upper()
    if method not in {"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"}:
        raise BadRequest("HTTP method is not supported by the relay")

    target = _target_url(path or frappe.request.args.get("path") or "/")
    status, body, headers = _fetch_upstream(target)
    frappe.local.back4app_relay_response = (status, body, headers)

    # Select the binary response builder; relay_after_request replaces its
    # placeholder body and headers with the exact upstream response.
    frappe.local.response["type"] = "binary"
    frappe.local.response["filecontent"] = b""
    frappe.local.response["filename"] = "relay-response"
    frappe.local.response["content_type"] = headers.get("Content-Type", "application/octet-stream")
    return None


def relay_after_request(response):
    """Restore upstream status, body, and end-to-end response headers."""
    relay_response = getattr(frappe.local, "back4app_relay_response", None)
    if relay_response is None:
        return response

    status, body, headers = relay_response
    response.status_code = status
    response.set_data(b"" if frappe.request.method.upper() == "HEAD" else body)

    # Remove headers generated by Frappe for the placeholder response, then
    # restore the upstream end-to-end headers. Frappe may append its own
    # tracing/security headers later in the request lifecycle.
    for key in list(response.headers):
        if key.lower() not in {"set-cookie", "cache-control"}:
            del response.headers[key]
    for key, value in headers.items():
        response.headers[key] = value
    return response
